# Generated by Django 4.2.1 on 2023-10-19 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("djf_surveys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="answered_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="answered_surveys",
                to=settings.AUTH_USER_MODEL,
                verbose_name="answered by",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
