# Generated by Django 4.2.1 on 2023-10-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djf_surveys", "0002_alter_survey_answered_by_alter_survey_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="label",
            field=models.TextField(
                help_text="Enter your question in here.", verbose_name="label"
            ),
        ),
    ]
