# Generated by Django 4.2.1 on 2023-10-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djf_surveys", "0004_alter_survey_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="key",
            field=models.CharField(
                blank=True,
                help_text="Unique key for this question, fill in the blank if you want to use for automatic generation.",
                max_length=900,
                null=True,
                unique=True,
                verbose_name="key",
            ),
        ),
    ]
